### ISSUE TITLE
Add Isle of Armor pokemon to the selection

### ISSUE THREAD

**Issue by Novocastrian** [richi3f-zz/candy-calc#4]
Hi there!

I'm sure you're aware of this already, but I'm logging this onto the issues board to track anyway. I believe all required pokemon ar as follows (I've ripped this off IGN, so I apologise if they've missed anything!)

Squirtle
Wartortle
Blastoise (and Gigantamax)
Bulbasaur
Ivysaur
Venasaur (and Gigantamax)
Fletchling
Fletchinder
Talonflame
Horsea
Seadra
Kingdra
Psyduck
Golduck
Happiny
Chansey
Blissey
Azurill
Marill
Azumarill
Dedenne
Zorua
Zoruark
Rockruff
Lycanroc
Larvesta
Volcarona
Magnemite
Magneton
Magnezone
Mienfoo
Mienshao
Shinx
Luxio
Luxray
Tauros
Scyther
Scizor
Druddigon
Whismur
Loudred
Exploud
Sandile
Krokorok
Krookodile
Exeggcute
Exeggutor
Tangela
Tangrowth
Poliwag
Poliwhirl
Poliwrath
Politoed
Kangaskhan
Emolga
Skrelp
Dragalge
Bouffalant
Staryu
Starmie
Formantis
Lurantis

**Comment by richi3f-zz** [comment]
The calculator has been updated with these Pokémon. :) If I missed something, please open a new issue. Thanks!
